import ctypes

WINDOW_WIDTH = ctypes.windll.user32.GetSystemMetrics(78)
WINDOW_HEIGHT = ctypes.windll.user32.GetSystemMetrics(79)
WIDTH_BUFFER, HEIGHT_BUFFER = 0.5 * WINDOW_WIDTH, WINDOW_HEIGHT
WINDOW_WIDTH_RANGE = (-WIDTH_BUFFER, WINDOW_WIDTH)
WINDOW_HEIGHT_RANGE = (-2 * HEIGHT_BUFFER, WINDOW_HEIGHT + HEIGHT_BUFFER)
